'use client';

import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {ArrowUpRight, ArrowRight, Menu, X} from 'lucide-react';
export const nav=[['Home','/'],['Products','/products'],['About us','/about'],['Distribution','/distribution'],['Contact us','/contact']];
export function Logo(){return <span className="logo"><b>mr<span>paints</span><i>.</i></b><small>COLOUR. PROTECT. INSPIRE.</small></span>}
export function Header(){const path=usePathname();const [open,setOpen]=useState(false);return <><div className="topbar"><span>Made for beautiful spaces. Built for everyday life.</span><a href="mailto:info@mrpaints.in">info@mrpaints.in <ArrowUpRight size={13}/></a></div><header className="header"><a href="/" aria-label="MR Paints home"><Logo/></a><nav className={open?'nav open':'nav'} aria-label="Main navigation">{nav.map(([label,href])=><a key={href} href={href} onClick={()=>setOpen(false)} aria-current={path===href?'page':undefined}>{label}</a>)}</nav><a className="header-cta" href="/contact">Let's talk colour <ArrowUpRight size={17}/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'} aria-expanded={open}>{open?<X/>:<Menu/>}</button></header></>}
export function Action({href,children,light=false}: {href:string,children:React.ReactNode,light?:boolean}){return <a className={'button '+(light?'light':'')} href={href}>{children}<ArrowUpRight size={19}/></a>}
export function Footer(){return <footer><div className="footer-main"><div><a href="/"><Logo/></a><p>Bringing colour to spaces.<br/>Bringing possibilities to life.</p></div><div><h3>Explore</h3>{nav.slice(1).map(([n,h])=><a key={h} href={h}>{n}</a>)}</div><div><h3>Start a conversation</h3><a className="footer-email" href="mailto:info@mrpaints.in">info@mrpaints.in <ArrowUpRight size={18}/></a><p>Manufacturing & distribution<br/>India</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} MR Paints. All rights reserved.</span><span>A fresh perspective. A beautiful finish.</span></div></footer>}
export function CTA(){return <section className="cta"><div><span className="eyebrow">YOUR NEXT CHAPTER, IN COLOUR</span><h2>Good things begin<br/>with a fresh coat.</h2></div><Action href="/contact" light>Talk to MR Paints</Action></section>}
export const products=[{title:'Interior paints',tag:'SPACES TO FEEL AT HOME',text:'Set the mood for everyday living with colour for bedrooms, living areas and shared spaces.',color:'#bc6950',finish:'For interior walls',id:'interior'},{title:'Exterior paints',tag:'A WELCOMING FIRST IMPRESSION',text:'Bring character to facades and outside walls. Find a coating suited to your surface and surroundings.',color:'#8c9c9c',finish:'For exterior walls',id:'exterior'},{title:'Enamels & finishes',tag:'THE FINISHING TOUCH',text:'Give doors, railings and details a considered finish, with options for wood and metal surfaces.',color:'#cfac53',finish:'For wood & metal',id:'enamels'},{title:'Primers & preparation',tag:'START WITH THE FOUNDATION',text:'Prepare your surface for the next coat. Ask our team about primers and the right preparation system.',color:'#c5c1b5',finish:'For surface preparation',id:'primers'}];
export function ProductCards({full=false}:{full?:boolean}){return <><div className="products-grid">{products.map((p,i)=><article className="product" id={p.id} key={p.id}><div className="product-color has-pack" style={{backgroundColor:p.color}}><span>MR / 0{i+1}</span><img className="product-pack" src="/images/mr-paint-bucket.png" alt="MR Paints illustrative packaging" loading="lazy"/><span className="color-word">{['Live','Protect','Refine','Prepare'][i]}<i>.</i></span><span>{p.finish}</span></div><div className="product-info"><h3>{p.title}</h3>{full&&<p>{p.text}</p>}<a href={full?`/contact?interest=${encodeURIComponent(p.title)}`:`/products#${p.id}`} aria-label={'Explore '+p.title}>{full?'Enquire about this range':'Explore range'}<ArrowRight size={17}/></a></div></article>)}</div><p className="pack-notice">Packaging shown is illustrative. Contact us for current products and pack sizes.</p></>}
